using System.ComponentModel.DataAnnotations;

namespace RagSystem.Core.DTOs.RAG;

public class RAGRequest
{
    [Required]
    [MaxLength(1000)]
    public string Question { get; set; } = string.Empty;

    [Range(1, 20)]
    public int TopK { get; set; } = 5;

    public bool UseHybrid { get; set; } = true;

    public bool UseAgentic { get; set; } = false;

    public string? Model { get; set; }

    /// <summary>
    /// Optional: Filter by specific uploaded file IDs. If empty, searches all documents.
    /// </summary>
    public List<Guid>? FileIds { get; set; }

    /// <summary>
    /// Optional: Filter by a specific advisory GHSA ID (e.g. "GHSA-xxxx-yyyy-zzzz").
    /// When set, retrieval is scoped to that advisory's indexed chunks only.
    /// </summary>
    public string? AdvisoryId { get; set; }

    /// <summary>
    /// Stable session identifier generated by the frontend per page load.
    /// Used to maintain conversation continuity in the Python RAG service.
    /// </summary>
    public string? SessionId { get; set; }

    /// <summary>
    /// Prior conversation turns to give the LLM context of the ongoing discussion.
    /// Each entry has "role" ("user" or "assistant") and "content".
    /// </summary>
    public List<ConversationTurn>? ConversationHistory { get; set; }
}

public class ConversationTurn
{
    public string Role { get; set; } = string.Empty;
    public string Content { get; set; } = string.Empty;
}

public class RAGResponse
{
    public string Question { get; set; } = string.Empty;
    public string Answer { get; set; } = string.Empty;
    public List<SourceDocument> Sources { get; set; } = new();
    public int ChunksUsed { get; set; }
    public string SearchMode { get; set; } = string.Empty;
    public List<string>? ReasoningSteps { get; set; }
    public double ResponseTimeMs { get; set; }
    public bool FromCache { get; set; } = false;
}

public class SourceDocument
{
    public string SourceId { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public List<string>? Authors { get; set; }
    public string? ChunkText { get; set; }
    public int ChunkIndex { get; set; }
    public double Score { get; set; }
}
